### PR TITLE
Add stub of a test program, correct a few notes and some tidying up

### PR DESCRIPTION
**Pull request by ukscone**
i've added the start of a test program and corrected a few notes etc.

### CODE REVIEW

**Comment by shawaj** [comment]
In setup.py do we need to have papirus-logo.png? and also, if so, it should be bin/papirus-logo.png same as others?

And in the README:

```
# Write text to the screen at selected point
# text.write(text, size, x,y)
+text.write("hello world", 20 10, 10 )
```

Should there not be a comma after 20? And what are changes in text.py about x and y axis for? Do we not need a definable size as well?

Other than that what is gitignore on .pyc for?

I think snakes and framepush code is done, just need to find out why they aren't here on git!

**Comment by ukscone** [comment]
sorry i think the missing comma was a typo that occurred when i was moving stuff from the dev directory to the repo dir as github was being a right PITA. you have the definable size in that function call.

the papirus-logo,png in setup.py was so it was moved/findable by the test prog as i didn't know where to put it so it was findable.

the .gitignore for the .pyc's is because it's bad form imho to put "compiled" programs in a repo

**Comment by shawaj** [comment]
In that function call we do, but in text.py we have got a defined size of 20 don't we?

**Comment by ukscone** [comment]
yes in text.py you have a default size of 20 (def write(self, text, size = 20):) and no positioning for where text starts (x,y) just start at top and split into screen sized lengths. my version isn't correct but worked for what was needed at the time and to "answer" complaint on twitter. does need redoing to conform to "the papirus way(tm))

**Comment by ukscone** [comment]
oh and unless i am very wrong to use the xaxis and yaxis in that function you have to use values for all things defined earlier in the call arguments. i don't think you can do papirus.write("hello,world!",,10,10)

you have to fill in the missing value. i think you can do papirus.write("hello,world!",20,10) and have the y axis use the default value

**Comment by shawaj** [comment]
I'm confused now. What is done the wrong way?

**Comment by ukscone** [comment]
basically your version of the write() function in text.py had no arguments for user positioning. I put in a quick hack to allow the user to position the text. However it's not neat and is probably not the correct way to do it. I only checked that it did what I expected most of the time, also the arguments are not in the order i'd like them or how you'd normally expect a function to position text to be. Without having two functions write() & write_xy() i can't see how to do it with the way variable number of arguments works in python.

lets take this to email or im

**Comment by ukscone** [comment]
ah just read some more python docs and I think I see the "correct" way to do it. i'll need to read through the code a bit and try a few things out but I think I have it sussed.

**Comment by shawaj** [comment]
I can't seem to merge because of conflicts but can just pick out all the changes probably and just load them in, unless you want to fix the conflicts?

**Comment by ukscone** [comment]
ok i'll do a clean pull of your repo and a clean of my version and try to work out the diffs

**Comment by shawaj** [comment]
Ok awesome, sounds good on all counts

**Comment by francesco-vannini** [comment]
Hi @ukscone,
could you please review this PR and see what is still applicable from when you created it and what has already been fixed/changed in the meantime.
I'll review after that if this is OK with you.
Thanks

**Comment by francesco-vannini** [comment]
@shawaj a part from the notes everything else has been implemented and documented.

**Comment by shawaj** [comment]
closing as no longer relevant

**Comment by shawaj** [comment]
.....and all issues have been fixed that this contains :-)

**Pull request closed without merging**
