### PR TITLE
papirus-write complained about missing parentheses

### PR DESCRIPTION
**Pull request by CleoQc**
It wouldn't run without this change, tested on a brand new Raspbian card

### CODE REVIEW

**Comment by francesco-vannini** [comment]
Hi Cleo, isn't it because you are using Python 3 that you get that?

**Comment by CleoQc** [comment]
Nope I'm using Python 2

**Comment by shawaj** [comment]
Strange - never seen that error before. How odd.

I have an old version sat on my desk with software already installed - will test with that.

@francesco-vannini have you tested with a new Raspbian as well?

If it works on both fine, then no reason to not add the ()

**Comment by CleoQc** [comment]
Also those files already use the parentheses for the print statements as this link shows:
https://github.com/PiSupply/PaPiRus/search?utf8=%E2%9C%93&q=print

So right now it's inconsistent the way it's currently done.

**Pull request merged**
