### PR TITLE
install package for papirus-temp

### PR DESCRIPTION
**Pull request by kurt77**
Added command to install "bc" and "i2c-tools" packages needed by papirus-temp.
(i hope this is the right file and place to add package installation lines)
papirus-temp print temperature on shell using papirus hat temperature sensor.

### CODE REVIEW

**Comment by shawaj** [comment]
Isn't i2c-tools included by default in Raspbian?

**Comment by kurt77** [comment]
I don't know..i have raspbian jessie
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

and the package was missing.
Anyway, i don't think "apt-get install i2c-tools" wont harm anyone if already installed.
Same thing for "bc"

**Comment by ukscone** [comment]
i2c-tools and bc are not in raspbian by default.

**Comment by shawaj** [comment]
Pulling this in now - see issue #30 also for more info

**Pull request merged**
