### PR TITLE
0 90 180 270 rotation

### PR DESCRIPTION
**Pull request by tvoverbeek**
Add rotation option so display can be used inverted and in portrait mode.
Allowed rotations are 0 (default), 90, 180 and 270 degrees.
Examples have also been updated to make use of rotation.

### CODE REVIEW

**Comment by francesco-vannini** [comment]
Hi Ton, only a minor thing in epd.py
#qCopyright 2013-2015 Pervasive Displays, Inc.
Just writing it here so that I can amend after PR

**Comment by tvoverbeek** [comment]
​Noticed this, but did not know how to change it.
Add an extra Copyright line with CopyRight PiSupply 2017 ???

T​

**Comment by francesco-vannini** [comment]
Nothing is by chance with you, I should have known better :) @shawaj what do you think we should do?

**Comment by shawaj** [comment]
What's the issue?

**Comment by Dom1n1c** [comment]
When will it be available?

**Comment by shawaj** [comment]
Soon

**Comment by francesco-vannini** [comment]
@tvoverbeek why did you remove the possible_fonts section in papirus-clock? Is it no longer needed?

**Comment by tvoverbeek** [comment]
Original code came from repaper and tried to care for many Linux flavours (Beaglebone Black, Ubuntu, etc.). Since the hardware is RPi specific I only left the safe Raspbian choice. Users, of course, can change, extend this if they choose.

**Pull request merged**
