### PR TITLE
Update buttons example script for PaPiRus Zero

### PR DESCRIPTION
**Pull request by digithree**
Add command line options to switch button pins to PaPiRus Zero mapping.
Use -z or --zero to activate. Defaults to standard mapping

### CODE REVIEW

**Comment by francesco-vannini** [comment]
Hi @digithree ,
thanks for this.
could this not be automatically done by checking if it is a HAT or not in the case of the Zero? Maybe by looking at I2C.
If that's not the case could you also provide a "usage" description for the main README.md?

**Comment by shawaj** [comment]
Could definitely be done by checking for the HAT EEPROM.

Or alternatively looking for the RTC

**Comment by digithree** [comment]
Hmm, I'm not sure how to do that. Could you point me in the right direction?

**Comment by shawaj** [comment]
If it's a HAT you should have a value of Pi Supply
in /proc/device-tree/hat/vendor and PaPiRus ePaper HAT v1.8 or v1.9 in
/proc/device-tree/hat/product

You can find them by putting "cat" in front of the address.

And also if it's a HAT you should have something connected to address 0x6F
on the I2C bus. That's the RTC.

Thanks

**Comment by tvoverbeek** [comment]
See my PR #77 which implements Aarons (shawaj) suggestion for HAT detection.

**Comment by francesco-vannini** [comment]
This has been sorted already in #77 and #79 so closing this PR

**Comment by digithree** [comment]
That's fine, glad it is apparently sorted. I'll check it out soon.

**Comment by shawaj** [comment]
Thanks for your code though

**Pull request closed without merging**
