### PR TITLE
PaPiRus Positional Text

### PR DESCRIPTION
**Pull request by BenScarb**
Simple class for doing positional text on the PaPiRus screen.

### CODE REVIEW

**Comment by shawaj** [comment]
Just out of interest, does this allow for line breaks also?

**Comment by BenScarb** [comment]
No, currently the code doesn't take line breaks in to account.
I'll take a look at that next.

**Comment by shawaj** [comment]
Awesome :-)

**Comment by BenScarb** [comment]
There we go, \n line breaks now supported :)

**Comment by shawaj** [comment]
Awesome. Do you think /r breaks are useful at all? Looks fantastic though.

**Comment by BenScarb** [comment]
Yes, probably worth taking in to account.  Also \r\n.
Using .splitlines() to do all three cases in one go :)

**Comment by shawaj** [comment]
Awesome, looks great. Thanks so much :-)

**Comment by francesco-vannini** [comment]
@BenScarb is there a way we could refactor papirus-write to include this new feature but end up with only one write approach instead of two?

**Comment by BenScarb** [comment]
I'll have a look, I thought papirus-write was a complied file!
Shouldn't be a problem to change it out, optional params for X and Y, then pass it all to the existing routines.
There wouldn't be any speed updates as it would happen once and then exit.

**Comment by shawaj** [comment]
The main idea behind it was really not for speed but just so that it isn't
confusing.... Could have one write command, with optional X,Y and if you
don't put an X,Y it just defaults to normal.

That's kind of what we were thinking

**Comment by shawaj** [comment]
@BenScarb realised I forgot to tag you in my last reply. Just wanted to check you saw it

**Comment by BenScarb** [comment]
No worries, I'll be taking a look tomorrow :)   Assuming I can find where I tidied my Pi away to!

**Comment by shawaj** [comment]
:-)

**Comment by BenScarb** [comment]
Found the Pi!  Sorted the papirus-write to accept the X and Y coords and use the appropriate code.
Updated the textpos class as the strings weren't being accepted as having a line break in, so needed to be (un-)escaped.  

Not sure what I've done to the ReadMe.md file, thought I'd fixed it, looked all right on http://dillinger.io/ but not do good on GitHub!

**Comment by francesco-vannini** [comment]
Ben I'll take a look at this next week, thanks for the effort, really appreciated and sorry it is taking so long to review this. Keep you posted.

**Comment by BenScarb** [comment]
No worries, I know life happens :)   If anything else needs updating or de-conflicting, just drop me a message.

**Comment by francesco-vannini** [comment]
Hi, I have finally tested the code which works really nicely, thanks! Only one thing now could you redo the README.md changes using the current file. That should also help cleaning up that strange behaviour you saw caused by you removing the "Your python script must be running with root privileges ... " part but you left behind one ```
Also if possible could you please clean up the various commits and collapse the new in just one as we did for #55
Many thanks once again. I'll merge as soon as I get the new changes.

**Comment by BenScarb** [comment]
No worries, I'll see if I can get the changes done tonight.   My "diffing skills" need working on me thinks, didn't see what I'd left behind!   Read up on the "needing root" stuff, good call.   I'll get the current ReadMe.MD updated and uploaded.

**Comment by BenScarb** [comment]
I have updated the README.md, I believe it's sorted but the conflict still exists.
Seems I need to research how to do that!  I think just taking the version from branch will do it :)

**Comment by shawaj** [comment]
Me and @francesco-vannini can probably fix it next week.

I think basically you just need to do a git rebase but then I'm also pretty
awful at git so it's like the blind leading the blind :-)

Let's all have a go next week and see if we can fix it

**Comment by BenScarb** [comment]
Great stuff, sorry I can't give you a fully formed branch to pull in.  Something for me to work on, every days a learning day :)

**Comment by shawaj** [comment]
No need to be sorry! It's awesome to have people like you contributing code
:-)

**Comment by BenScarb** [comment]
Once this is merged in, I'll take a look at inverting the colours, or at least having control over them :)
The White on Black seems like a good idea!

**Comment by shawaj** [comment]
Yeah definitely. Someone's just mentioned it in #80 actually

**Comment by francesco-vannini** [comment]
Thanks a lot @BenScarb - all sorted and merged now :-)

Thanks so much for your contribution!

**Comment by BenScarb** [comment]
Woohoo, my first proper submissions and completed PR!
Glad it'll be useful :)

**Comment by shawaj** [comment]
Yes indeed, we just copy pasted the readme as we couldn't be bothered to
fix it "the proper way" :-)

**Pull request merged**
