### PR TITLE
Created a new papirus-temp

### PR DESCRIPTION
**Pull request by francesco-vannini**
Added float methods to lm75b.py

### CODE REVIEW

**Comment by shawaj** [comment]
Sweet nice one. Guess we need Ton to test it? Is that why you didn't just push it straight to master?

Also, not that it really matters but if you wrote it it probably doesn't need to be copyright Pervasive Displays.

**Comment by francesco-vannini** [comment]
Yeah you are right too much copy/paste. I'll remove that.
I wanted @tvoverbeek to have a look just in case. It works fine so there shouldn't be any issues.

**Comment by shawaj** [comment]
Sweet nice one

**Comment by francesco-vannini** [comment]
Merged into #135

**Pull request closed without merging**
