### PR TITLE
added textfill commandline argument

### PR DESCRIPTION
**Pull request by dramsay9**
I wrote this command line tool to center one line of text on the screen and make it as large as possible for the screen size.  It takes one argument - the string to print - and centers/sizes it appropriately.

`sudo papirus-textfill "hello world"`  

Handles up to 40 chars well, if the input is larger than 40 it will truncate it to 40.

### CODE REVIEW

**Comment by shawaj** [comment]
Looks great. Is there a restriction on line length and what happens if you write a large amount of text? Does it wrap to next lines?

Just want usage notes to add to readme

**Comment by dramsay9** [comment]
hey @shawaj!  It won't wrap, it simply truncates anything longer than 40 chars to the first 40 and prints it all on one line (centered, with as large a fontsize as will still fit on the screen).

**Comment by shawaj** [comment]
Awesome. Can you do a pull request adding that info to the main readme at
the bottom any we will accept both?

**Comment by dramsay9** [comment]
I added it to the bottom of the command line section-- happy to put it under demos instead if that makes more sense (wasn't sure).  Let me know if you have other comments!

**Comment by shawaj** [comment]
I think that'll be fine. We need to tidy up and overhaul the readme anyway
at some point because it's a bit of a mess and some of our outdated.

As long as it's there somewhere for now that's great :-)

**Comment by dramsay9** [comment]
cool!  I think it should be ready to merge :)

**Comment by francesco-vannini** [comment]
Checked and tested. Resolved a conflict with the README.md file, we'll also need to change the script to root check as in #79. Will mark as issue and solve straight away.

**Comment by francesco-vannini** [comment]
Thanks @dramsay9

**Pull request merged**
