### PR TITLE
Update to read scale operation

### PR DESCRIPTION
**Pull request by sKoeberle**
It’s just a correction to display at the correct scale.

### CODE REVIEW

**Comment by shawaj** [comment]
this is in relation to issue #60 

@sKoeberle there is a conflict with the file you sent - can you resolve it?

**Comment by shawaj** [comment]
also @sKoeberle can you give us a bit of info as to what the purpose of this change is, and how it would be used? so we can update readme

**Comment by francesco-vannini** [comment]
Hi @sKoeberle, when did you branch out the code? You are not working on the latest version of papirus-temp it seems to me

**Comment by shawaj** [comment]
also @sKoeberle did you see my message above?

"Can you give us a bit of info as to what the purpose of this change is, and how it would be used? so we can update readme?"

**Comment by sKoeberle** [comment]
It’s just a little correction to display characters at the correct scale when scale is indicated as here: "scale=3". Without this modification, changing the scale hasn't any effects on display.

**Comment by francesco-vannini** [comment]
Hi, really appreciate your help here but the file had already been changed to that, please have a look at it in the current version https://github.com/PiSupply/PaPiRus/blob/master/bin/papirus-temp

**Comment by francesco-vannini** [comment]
@sKoeberle I'll close this. By all means I am happy to reopen this again if I didn't understand what you were getting at.

**Pull request closed without merging**
