### PR TITLE
Minor typo and wording fixes in README

### PR DESCRIPTION
**Pull request by VirtualWolf**
Just some very tiny fixes.

### CODE REVIEW

**Comment by shawaj** [comment]
Thanks! Mostly look ok but line 339 and 340 doesn't look complete?

**Comment by shawaj** [comment]
Also noticed that PaPiRus is capitalised incorrectly in a few places...

**Comment by VirtualWolf** [comment]
> Thanks! Mostly look ok but line 339 and 340 doesn't look complete?

Hm, yeah, it could be improved... I assume the library will always just show the images in filename order, right? And it's just if you have an animation you need to name them in some sort of sequence where they'll be read in the right order (be it `0.gif`, `1.gif`, `2.gif` or `a.gif`, `b.gif`, `c.gif`)?

> Also noticed that PaPiRus is capitalised incorrectly in a few places...

Ah, good catch. It was tricky picking them out in between the places in the code examples where it's _meant_ to be just "Paprius", heh.

**Comment by shawaj** [comment]
Yeah I'll correct those later.

About the mine 339 and 340 it was more that there was some text removed that shouldn't have been.

Just wondered if this was intentional and if so, then why?

**Comment by francesco-vannini** [comment]
PaPiRus animation can also be used as a slide show without any specific order for the pictures and with a few more picture formats allowed. The original description can be found in c93ecce374388e4352867ad8a7e384a4334e5b7e
```
 # Display image sequences or slide-show
 +The path containing the pictures must have number sequenced images in the form 1.gif, 2.gif, 3.gif, etc. for an animation or pictures with random names (e.g. in the case of a slide-show). 
  papirus-animation path [rotation] [delay] [fullupdate] [loop]
```

**Comment by VirtualWolf** [comment]
> Just wondered if this was intentional and if so, then why?

Trying to make things a bit less wordy and clearer. :) I've updated it again, and fixed the Paprirus -> PaPiRus as well.

**Comment by tvoverbeek** [comment]
@VirtualWolf Thanks for the corrections. Apologies for the delay in merging.

**Comment by VirtualWolf** [comment]
No worries, cheers!

**Pull request merged**
